### PR TITLE
Changed DistributionTables values to match Notebook:

### PR DESCRIPTION
**Pull request by pkubanek**
https://github.com/lsst-ts/ts_notebooks/blob/develop/bxin/ptg2m1m3/FATABLE.py

### CODE REVIEW

**Review by bxin — COMMENTED** [review]
For the record, this notebook shows how I checked these force distributions, i.e., why they make sense. https://github.com/lsst-sitcom/M1M3_ML/blob/master/FB_diagnostics.ipynb

Further requests:

The moment distributions were all normalized to 0.001 N*m, which seems odd to me. Can you check that this is taken into account properly when these distributions are applied?

I suggest that we change it to 1N*m.

We should add comments to these data files about the normalizations.

Related to this, let's also update HardpointForceMomentTable.csv. I sent you Felipe's slides before. We agreed that we would update that matrix so that the moments are centered on the mirror back plate instead of the CG, but it looks like the table was never updated.
It would also be good if we add comments to the table about where the moments are centered. (I am OK with it if you want to make a separate PR).

**Comment by pkubanek** [comment]
Forces looks reasonable (1000N X moment offset)
obrazek

**Comment by pkubanek** [comment]
Let's make another PR for comments in tables and for HardpointForceMomentTable

**Review by bxin — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
